# html lang
language: zh-CN

# header
site_brand_name: é˜¿çŠ‡çš„è‡ªç•™åœ°

logo_image:
  enable: true
  image_path: ./images/avatar.png # path to your logo image

menu:
  æˆ‘çš„åšå®¢: /archives/
  å…³äºæˆ‘: /about/
  æˆ‘éƒ½åšäº†å•¥: /my-projects/
# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/menu.js

# favicon
favicon: ./images/favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: ğŸ‘‹ï¼Œé˜¿çŠ‡çš„è‡ªç•™åœ°
  body: æˆä¸ºå¤šç»´åº¦çš„äººğŸ‘¨â€ğŸ’»ğŸ‘·ğŸ¤¹ğŸ§™â€â™€ï¸ğŸ‘¨â€ğŸ¼
  image: ./images/profile_cover.jpg

  links:
    åšå®¢: /archives/
    å…³äº: /about/
    äº§å“: /my-projects/
    RSS: /atom.xml
    #Resume: /path/to/your/resume.pdf å…³äºç›¸å¯¹è·¯å¾„çš„è®¾ç½®ã€‚

# footer
footer:
  copyright_info:
    enable: true
    author: Â©é˜¿çŠ‡

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: false
    content:

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false

# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: false
  appId: # Your valine app Id
  appKey: # Your valine app Key
  lang: "zh-CN"
  placeholder: "Say something"
  avatar: "mp"
  meta: ["nick", "mail"]

disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: true
  disqus_url: https://weber36.me/ # your diqsuq url or shortname
  language: "zh-CN"

# local search
local_search:
  enable: false
  place_holder: Search Anything
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: 1 # show top n results per article, show all results by setting to -1
  unescape: false # unescape html strings to the readable one
  preload: false # reload the search data when the page loads, this will accelerate the search process

